
library(ggplot2)
library(RColorBrewer)
data<-read.table("envio.txt")
colourCount = length(unique(data$V2))
getPalette = colorRampPalette(brewer.pal(9, "Set1"))
pdf("envio.pdf")
p<-ggplot(data,aes(V1,V3,fill=V2))+geom_bar(stat = "identity",position = "fill")+scale_fill_manual(name="Taxid",values = getPalette(colourCount))+theme_bw()+xlab("Sample")+ylab("Abundence")
print(p,width=4,height=2)
dev.off()
